sonar.projectKey=LineLsr_open-classrooms-bobapp-2026
sonar.organization=linelsr

sonar.sources=back/src/main
sonar.tests=back/src/test
sonar.java.binaries=back/target/classes
sonar.coverage.jacoco.xmlReportPaths=back/target/site/jacoco/jacoco.xml

sonar.javascript.lcov.reportPaths=front/coverage/bobapp/lcov.info