name: CI/CD Pipeline

  on:
    push:
      branches: [ main, dev ]
    pull_request:
      branches: [ main ]

  jobs:
    hello:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout du code
          uses: actions/checkout@v3

        - name: Premier pas
          run: echo "Le workflow fonctionne !"